# platform :ios, '9.0'

target 'mc' do
  #use_frameworks!

  pod 'SwiftSocket'
end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     puts "#{target.name}"
#     target.build_configurations.each do |config|
#       config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
#       config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
#       config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
#     end
#   end
# end
